version: 2

models:
  - name: outbrain_campaigns
    columns:
    - name: active
      tests:
      - not_null

    - name: currency
      tests:
      - not_null

    - name: id
      tests:
      - not_null
      - unique

    - name: name
      tests:
      - not_null

    - name: spend
      tests:
      - not_null

  - name: outbrain_campaign_performance
    columns:
    - name: campaign_id
      tests:
      - not_null

    - name: date_day
      tests:
      - not_null

    - name: id
      tests:
      - not_null
      - unique

    - name: spend
      tests:
      - not_null
